### PR TITLE
Draft: Add BuildInfo

### PR DESCRIPTION
**Pull request by cristaloleg**

### CODE REVIEW

**Comment by GreyXor** [comment]
No more Version info ?

**Comment by cristaloleg** [comment]
@GreyXor are you referring to `Version string` field?

**Comment by GreyXor** [comment]
Yes, this PR had the `Version string` field and it was about using this : https://github.com/cristalhq/acmd/blob/main/GUIDE.md#build-version
It's cancelled ?

**Comment by cristaloleg** [comment]
Got it. I wasn't happy with the API after all. I will convert this PR to draft to not disrupt anyone for some time.

Also, `go build -ldflags="-X 'github.com/cristalhq/acmd.Version=vFoo.Bar.Baz'" -o my_binary .` looks horrible, `main.Version` looks much simpler and says much more in less words.

I will try to hack something this week, stay tuned (or share your ideas! thanks)

**Comment by GreyXor** [comment]
Thanks!

**Comment by cristaloleg** [comment]
Will be a part of https://github.com/cristalhq/appx

**Pull request closed without merging**
