### PR TITLE
Add options feature

### PR DESCRIPTION
**Pull request by mntcloud**

### CODE REVIEW

**Comment by cristaloleg** [comment]
Hi, thanks for the PR, can you clarify what is the reason behind this feature? I dont get it reading code. Looks like it's Runner config but still something else.

**Comment by mntcloud** [comment]
The reason behind this feature is to add a new structure called `Option`:
```go
type Option struct {
	// Name of the option, example: `--help`
	Name string

	// Short name of the option, example: `-h`
	ShortName string

	// Description of the option
	Description string

	// Will return default value, in case if the option is not mentioned
	DefaultValue func() string
}
```
For example, in a production app, an option looks like this:
```sh
someapp --port ":3000"
```
Indifference between `acmd.Option` and `acmd.Command`, the main purpose of the `acmd.Option` is to store a value from the user or calculate the default value, in case the user didn't provide a value. 

`acmd.Option`'s values can be accessed in any command or parsed and used only in the local context of the command

**Comment by cristaloleg** [comment]
Hm, that sounds like a flag, global flag, am I right? If so, please take a look at #19 I've published it not so long time ago.

Looks like the case is to define global flag set (by example `type option struct { ... }`) and just parse it in every command. WDYT?

**Comment by mntcloud** [comment]
I think, it is one of good solutions for the case, but I think we can simplify work with retrieving values from the flags.
What about parsing options(flags) in the `Runner.init()` and retrieving values via the `context.Context`?
Take a look at an example app:
```go
package main

import (
    "fmt",
    "github.com/mntcloud/acmd",
    "log"
)

func main() {
	cmds := []Command{
		{
			Name:        "foo",
			Description: "some description",
			Do: func(ctx context.Context, args []string) error {
				val := acmd.AccessContext(ctx, "option")

				fmt.Println(val)

				return nil
			},
		},
	}

	opts := []Option{
		{
			Name:         "option",
			ShortName:    "opt",
			Description:  "something",
			DefaultValue: func() string { return "hello" },
		},
	}

	r := RunnerOf(cmds, opts, Config{
		Args:           []string{"./someapp", "--option", "somevalue", "foo"},
		AppName:        "someapp",
		AppDescription: "someapp is a test application.",
	})

	if err := r.Run(); err != nil {
		log.Fatal(err)
	}
}
```
A small snippet from the `Runner.init` function:
```go
if r.opts != nil {
	if err := ParseOptions(&r.args, &r.ctx, r.opts, bakeExclude(r.cmds)); err != nil {
		return err
	}
}
```

**Comment by cristaloleg** [comment]
> we can simplify work with retrieving values from the flags.

How? I don't get it from your example :( also, what is the point to use new []Option type when badically it's a FlagSet?

**Comment by mntcloud** [comment]
> How?

Using the `acmd.AccessContext(ctx context.Context, key string)` function, because options, which are defined before any command, ex. `someapp --opt value run`, it's values are passed as an argument to the `ctx` parameter in the `Command.Do` function.

**Comment by cristaloleg** [comment]
Sorry, I don't see big improvements over simple flagset that can be defined outside of `acmd` and be reused by every handler :(

**Comment by mntcloud** [comment]
I've again taken a look at #19 and my example, and, in my opinion, with []Option code will only grow bigger than with the `withCommonFlags` function, so I will close my pull request.

Anyway, thanks for reviewing this :)

**Comment by cristaloleg** [comment]
Thanks, so merging #19 and making a release. Thank you for the discussion.

**Pull request closed without merging**
